### ISSUE TITLE
configuring issue

### ISSUE THREAD

**Issue by prateek-sparx** [carloscabo/responsive-youtube-player-with-playlist#2]
Hi Carlos,

I m facing while configure the API,
It gives me "NetworkError: 410 Gone - http://gdata.youtube.com/feeds/api/playlists/PL2591DC20C4BB4D78?v=2&alt=json&callback=jQuery111300009907489479589193_1440425100797&_=1440425100798"

Thanks
Prateek

**Comment by carloscabo** [comment]
Hi. The RSS Feed used to get the playlist contens was deprecated in the past weeks by YouTube. I'm upgrading the library to use YT API V3.0 (using an API KEY) Hope will beready to test in 2 or 3 days.

**Comment by carloscabo** [comment]
I've just uploaded the new version updated to the V3 of Youtube API. Some testing it's in progress but seems that work fine with modern browsers.
