### ISSUE TITLE
Can i use custom youtube player here ?

### ISSUE THREAD

**Issue by swaranan** [carloscabo/responsive-youtube-player-with-playlist#6]
Hi, very nice js it is. But can I use it with a custom youtube player like ( plyr )...

**Comment by carloscabo** [comment]
I have no idea... I never tried, but probably would NOT be easy, all custom JS players usually have a very different html structure from the standard YT embed tags... (mainly iframes), custom JS events and callbacks... depending on the JS of each player... etc.

**Comment by swaranan** [comment]
Ok, Thanks, Let it try and see what happend..
