### ISSUE TITLE
No scrolling on iPhone

### ISSUE THREAD

**Issue by neworigin** [carloscabo/responsive-youtube-player-with-playlist#8]
I can't get the playlist to scroll when swiping on iPhone.

**Comment by egbradshaw** [comment]
Hello,

I have just implemented this and noticed the same thing on Android Chrome. 

Even on desktop using the demo, if you set the debugger to "Mobile" mode and squeeze down to 320px screen size, try to scroll one of the playlist areas, it just loads the video on point of click, even if you are still attempting to drag for scrolling.

This could be a major issue for mobile users and ruins the experience of this nice player.

Is this project still being updated/maintained? @neworigin's post is from last Nov and the issue clearly still exists.

**Comment by KarimDarwish** [comment]
Replace this:
```javascript
 D.$items.on('click touchstart', 'li', function(e) {
```

with 

```javascript
 D.$items.on('click', 'li', function(e) {
```

Scrolling should now be possible on touch screen devices.

**Comment by egbradshaw** [comment]
Thanks Karim! I can confirm that works.

**Comment by carloscabo** [comment]
Added to v2.22
