### ISSUE TITLE
Not working in Chrome v56

### ISSUE THREAD

**Issue by xcartmods** [carloscabo/responsive-youtube-player-with-playlist#9]
Well, sometimes it does, sometimes not. Works fine in Firefox and IE11.

In your demo, the console displays...

htmlpreview.min.js:1A Parser-blocking, cross-origin script, http://query.yahooapis.com/v1/public/yql?q=use%20%22https%3A%2F%2Fraw.githu…%2Fdemo.html%22&format=json&diagnostics=true&callback=HTMLPreview.loadHTML, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
send @ htmlpreview.min.js:1
init @ htmlpreview.min.js:1
(anonymous) @ ?http://raw.githubusercontent.com/carloscabo/responsive-youtube-player-with-playlist/master/demo.ht…:42
htmlpreview.min.js:1Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://raw.githubusercontent.com/carloscabo/responsive-youtube-player-with-playlist/master/css/RYPP.css".
(anonymous) @ htmlpreview.min.js:1
htmlpreview.min.js:1 A Parser-blocking, cross-origin script, http://query.yahooapis.com/v1/public/yql?q=use%20%22https%3A%2F%2Fraw.githu…ss%2FRYPP.css%22&format=json&diagnostics=true&callback=HTMLPreview.loadCSS, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
send @ htmlpreview.min.js:1
replaceAssets @ htmlpreview.min.js:1
(anonymous) @ ?http://raw.githubusercontent.com/carloscabo/responsive-youtube-player-with-playlist/master/demo.ht…:1
htmlpreview.min.js:1 A Parser-blocking, cross-origin script, http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
replaceAssets @ htmlpreview.min.js:1
(anonymous) @ ?http://raw.githubusercontent.com/carloscabo/responsive-youtube-player-with-playlist/master/demo.ht…:1
htmlpreview.min.js:1 A Parser-blocking, cross-origin script, http://query.yahooapis.com/v1/public/yql?q=use%20%22https%3A%2F%2Fraw.githu…2Fjs%2FRYPP.js%22&format=json&diagnostics=true&callback=HTMLPreview.loadJS, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by carloscabo** [comment]
Not related to the library itself.
